services:
  ingest:
    build: 
      context: ./data_ingestion
      dockerfile: Dockerfile.ingest
    command: python app.py
    network_mode: "host"
    environment:
      - SERVING_URL=http://${HOST_IP}:5002/predict
      - DRIFT_URL=http://${HOST_IP}:5003/drift
    volumes:
      - ./data/churn-model:/data/churn-model

  training:
    build:
      context: ./model_training
      dockerfile: Dockerfile.training
    command: python train.py
    network_mode: "host"
    volumes:
      - ./data/churn-model:/data/churn-model

  serving:
    build:
      context: ./model_serving
      dockerfile: Dockerfile.serving
    command: python serve.py
    network_mode: "host"
    volumes:
      - ./data/churn-model:/data/churn-model

  drift:
    build:
      context: ./drift_detection
      dockerfile: Dockerfile.drift
    command: python drift_detection.py
    network_mode: "host"
    environment:
      - TRAINING_URL=http://${HOST_IP}:5001/train
    volumes:
      - ./data/churn-model:/data/churn-model

volumes:
  shared-pvc: