FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y curl

COPY train.py .

EXPOSE 5001

CMD ["python", "-u", "train.py"]
