apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
      - name: model-serving
        image: kirtinigam003/model_serving:latest
        resources:
          requests:
            cpu: "100m"      # 0.1 CPU core
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 5002
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:                
        - name: churn-model-storage
          mountPath: /data/churn-model 
      volumes:                      
      - name: churn-model-storage
        persistentVolumeClaim:
          claimName: churn-model-pvc
