apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        image: kirtinigam003/data_ingestion:latest
        ports:
        - containerPort: 5000
        env:
        - name: TRAINING_URL
          value: http://model-training-service.default.svc.cluster.local:5001/train
