apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: kirtinigam003/model_training:latest
        ports:
        - containerPort: 5001
        volumeMounts:                
        - name: churn-model-storage
          mountPath: /app
      volumes:                      
      - name: churn-model-storage
        persistentVolumeClaim:
          claimName: churn-model-pvc
