apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
      - name: model-serving
        image: kirtinigam003/model_serving:latest
        ports:
        - containerPort: 5002
        volumeMounts:                
        - name: churn-model-storage
          mountPath: /app
      volumes:                      
      - name: churn-model-storage
        persistentVolumeClaim:
          claimName: churn-model-pvc
