---
- name: Include encrypted secrets
  include_vars: vars/secrets.yml

- name: Log into Docker Hub
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
    
- name: Install prerequisite packages
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
    update_cache: yes
    cache_valid_time: 3600 # Don't update if it was updated in the last hour
  register: apt_res
  until: apt_res is success
  retries: 5
  delay: 10

- name: Install Python venv package
  apt:
    name: python3.10-venv
    state: present
    update_cache: yes

- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key (Modern Way)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker-ansible
    update_cache: yes
  ignore_errors: yes
  
- name: Install Docker Engine
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
    update_cache: yes

- name: Ensure Jenkins user is in Docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  notify: Restart Docker
